# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: | 
       pwd
    - run: npm run build --if-present
    - run: npm test
  
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v1
#       - name: npm install and build webpack
#         env:
#           remote_host: ${{ secrets.SSH_HOST }}
#           remote_user: ${{ secrets.SSH_USERNAME }}
#           remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
#           local_dir: "/my-app"
#           remote_dir: "/var/www/html/my-app"
#         run: |
#           ls -l
#           mkdir ~/.ssh
#           echo "$remote_key" > ~/.ssh/gh_actions_key
#           chmod 600 ~/.ssh/gh_actions_key
#           rsync -avzr --delete -e "ssh -i ~/.ssh/gh_actions_key -o StrictHostKeyChecking=no" ${local_dir} ${remote_user}@${remote_host}:${remote_dir}
    
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: home/runner/work/my-app/
        remote_path: /var/www/html/my-app
        remote_host: ec2-54-255-247-179.ap-southeast-1.compute.amazonaws.com
        remote_user: ubuntu
        remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

